config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notes/index'
  get 'home/index'
  devise_for :users
  resources :notes, only: %i[new create edit update destroy]
  root to: 'notes#index'
  get 'tags/:tag', to: 'notes#index', as: :tag
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :date, presence: true
  belongs_to :user, required: true
  validates :user_id, presence: true
  acts_as_taggable_on :tags
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
  has_many :notes
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    helper_method :mobile?

  private

  def mobile? # has to be in here because it has access to "request"
    request.user_agent =~ /\b(Android|iPhone|iPad|Windows Phone|Opera Mobi|Kindle|BackBerry|PlayBook)\b/i
  end

  protected

  def configure_permitted_parameters
    attributes = %i[username email avatar]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[edit update destroy show]
  before_action :set_notes

  def index
    @note = current_user.notes.new
  end

  def new
    @note = current_user.notes.new
  end

  def create
    @note = current_user.notes.new(note_params)
    if @note.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @note.update(note_params)
      redirect_to root_path
    else
      flash[:notice] = 'note was not updated'
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    flash[:notice] = 'Note was deleted'
    redirect_to root_path
  end

  private

   def set_notes
    @notes = if params[:tag]
               current_user.notes.tagged_with(params[:tag]).order(date: :desc).paginate(page: params[:page], per_page: 6)
             else
               current_user.notes.order(date: :desc).paginate(page: params[:page], per_page: 6)
             end
  end

  def note_params
     params.require(:note).permit(:date, :title, :instructor, :technique, :sparring, :partner, :tag_list)
  end

  def set_note
    @note = Note.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def format_date(note)
    note.date.strftime("#{note.date.day.ordinalize} %b %Y")
  end

  def short_format_date(note)
    note.date.strftime("%a #{note.date.day.ordinalize} %b")
  end

  def table_header(url)
    if url.include? 'tags'
      request[:tag].parameterize(separator: '_')
    elsif url.include? 'notes/new'
      'New Note'
    elsif url.include? 'notes' && 'edit'
      "##{@note.id}"
    else
      'All Notes'
    end
  end

  def format_title(note)
    note.title.parameterize(separator: '_').downcase if note.title
  end

  def format_tags(note)
    note.tag_list.map do |tag|
      tag.parameterize(separator: '_').downcase
    end
  end

  def show_tag_toggle(url)
    if url.include? 'notes/new'
      false
    elsif url.include? 'notes' && 'edit'
      false
    else
      true
    end
  end
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassnotesBuild3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%# SIDEBAR %>
 
<% if user_signed_in? %>
 <%= render 'shared/nav2' %>
  <div id="main">
  <%= render 'shared/topnav' %>
  <% end %>
  <%= yield %>
  </div>
  <%= render 'shared/footer'%>
<script>

function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

/* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft = "0";
}
</script>
  
</body>
</html>

app/views/notes/edit.html.erb
<%= render 'shared/form2' %>

app/views/notes/index.html.erb
<% if mobile? %>
<%= render 'shared/mobtable'%>
<% else %>
<%= render 'shared/table' %>
<% end %>

app/views/notes/new.html.erb
<%= render 'shared/form2' %>

app/views/shared/_footer.html.erb
<div class="page_footer">
<p>© ClassNotes 2021</p>
<p>Arthur Fincham</p>
</div>

app/views/shared/_form2.html.erb
<div class="note-form-wrapper">
  <%= simple_form_for @note do |f| %>
  <div class="form_headers">
    <%= f.date_field :date %>
    <%= f.input :title, label: 'class'%>
    <%= f.input :instructor, label: 'instructor'%>
    <%= f.input :partner, label: 'partner'%>
  </div>
  <div class="tag_list_input">
  <%= f.input :tag_list, label: 'tags (seperated by commas)'%>
  </div>
  <div class="form_group">
    <%= f.input :technique, as: :text, label: 'technique' %>
    <%= f.input :sparring, as: :text, label: 'sparring' %>
  </div>
  <%= f.button :submit %><br>
  <% if request.path_info.include? 'notes' && 'edit' %>
  <%= link_to "Delete", note_path(@note), method: :delete, data: {confirm: "Are you sure?"}, class: "btn", id: "delete-note"%>
  <% end %>
  <% end %>
  
</div>

app/views/shared/_messages.html.erb
 <div class="error-box">
 <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>

app/views/shared/_mobtable.html.erb
<table class="table w-auto" id="fixedheight-table">
  <thead>
    <tr>
      <th scope="col">
        <h1>Class</h1>
      </th>

      <th scope="col">
        <h1>Summary</h1>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
    <tr data-link="<%= edit_note_path(note)%>">
      <td class="table-vert-line"><%= format_date(note) %><br><p class="notetitle"><%= format_title(note)%></p><%= note.instructor.downcase%></td>
      <td><%= truncate(note.technique, :length => 100, :separator => '') %><br><br><% format_tags(note).each do |tag| %>
        <button class="tag-badge"><%= "##{tag}" %></button>
      <% end %></td> 
    </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_nav.html.erb
   <ul class="nav-top-links">
     <li class="nav-item">
       <%= link_to new_note_path, method: :get, class: "nav-link align-middle px-0" do %>
       <span class="ms-1  d-sm-inline">New Note</span>
       <% end %>
     </li>

     <li class="nav-item">
       <%= link_to root_path, class: "nav-link align-middle px-0" do %>
       <span class="ms-1  d-sm-inline">All Notes</span>
       <% end %>
     </li>

   </ul>
   <ul class="nav-bottom-links">
     <li class="nav-item">
       <%= link_to edit_user_registration_path, method: :get, class: "nav-link align-middle px-0" do %>
       <span class="ms-1  d-sm-inline">Profile</span>
       <% end %>
     </li>

     <li class="nav-item">
       <%= link_to destroy_user_session_path, method: :delete, class: "nav-link align-middle px-0" do %>
       <span class="ms-1  d-sm-inline">Sign Out</span>
       <% end %>
     </li>

   </ul>

app/views/shared/_nav2.html.erb
 <div id="mySidebar" class="sidebar">
   <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
   <ul class="nav-top-links">
     <li class="nav-item">
       <%= link_to new_note_path, method: :get, class: "nav-link align-middle px-0" do %>
       <span class="ms-1  d-sm-inline">New Note</span>
       <% end %>
     </li>

     <li class="nav-item">
       <%= link_to root_path, class: "nav-link align-middle px-0" do %>
       <span class="ms-1  d-sm-inline">All Notes</span>
       <% end %>
     </li>

   </ul>
   <ul class="nav-bottom-links">
     <li class="nav-item">
       <%= link_to edit_user_registration_path, method: :get, class: "nav-link align-middle px-0" do %>
       <span class="ms-1  d-sm-inline">Profile</span>
       <% end %>
     </li>

     <li class="nav-item">
       <%= link_to destroy_user_session_path, method: :delete, class: "nav-link align-middle px-0" do %>
       <span class="ms-1  d-sm-inline">Sign Out</span>
       <% end %>
     </li>

   </ul>

 </div>

app/views/shared/_sidenav.html.erb
<div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-light">

  <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">

    <a href="" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <span class="fs-5 d-none d-sm-inline">Menu</span>
    </a>

    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">

      <li class="nav-item">
        <%= link_to new_note_path, method: :get, class: "nav-link align-middle px-0" do %>
        <i class="fs-4 bi-pen"></i> <span class="ms-1 d-none d-sm-inline">New Note</span>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to root_path, class: "nav-link align-middle px-0" do %>
        <i class="fs-4 bi-journal"></i> <span class="ms-1 d-none d-sm-inline">All Notes</span>
        <% end %>
      </li>

      <li>
        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
          <i class="fs-4 bi-tags"></i> <span class="ms-1 d-none d-sm-inline">Tags</span> </a>
        <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
        <% tag_cloud @notes.tag_counts.order("tags.name"), %w[m] do |tag| %>
          <li class="w-100">
          <span class="d-none d-sm-inline"><%= link_to "#{tag.name.parameterize(separator: '_')}", tag_path(tag.name), class: "nav-link px-0"%></span>
          </li>
          <% end %>
        </ul>
      </li>


      <li>
        <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
          <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Instructors</span></a>
        <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
        <% tag_cloud @notes.instructor_counts.order("tags.name"), %w[m] do |tag| %>
          <li class="w-100">
          <span class="d-none d-sm-inline"><%= link_to "#{tag.name.parameterize(separator: '_')}", instructor_path(tag.name), class: "nav-link px-0"%></span>
          </li>
          <% end %>
        </ul>
      </li>

      <li>
        <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
          <i class="fs-4 bi-columns-gap"></i> <span class="ms-1 d-none d-sm-inline">Classes</span> </a>
        <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
          <% tag_cloud @notes.note_title_counts.order("tags.name"), %w[m] do |tag| %>
          <li class="w-100">
          <span class="d-none d-sm-inline"><%= link_to "#{tag.name.parameterize(separator: '_')}", note_title_path(tag.name), class: "nav-link px-0"%></span>
          </li>
          <% end %>
        </ul>
      </li>


    </ul>

    <hr>
    <div class="dropdown pb-4">
      <a href="#" class="d-flex align-items-center text-gray text-decoration-none dropdown-toggle" id="dropdownUser1"
        data-bs-toggle="dropdown" aria-expanded="false">
        <img
          src="https://www.pngitem.com/pimgs/m/421-4212266_transparent-default-avatar-png-default-avatar-images-png.png"
          alt="hugenerd" width="30" height="30" class="rounded-circle">
        <span class="d-none d-sm-inline mx-1"><%= current_user.username %></span>
      </a>
      <ul class="dropdown-menu dropdown-menu-light text-small shadow" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item"><%= link_to "Profile Settings", edit_user_registration_path, method: :get %></a>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li>
        <li><a class="dropdown-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></a></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_table.html.erb
<%= render 'shared/tagcloud' %>

<table class="table" >
  <thead>
    <tr>
      <th scope="col"><h1>Class</h1></th>
      <th scope="col"><h1>Tags</h1></th>
      <th scope="col"><h1>Technique</h1></th>
      <th scope="col"><h1>Sparring</h1></th>
      <th></th>
    </tr>
  </thead>
  <tbody>

  <tr class="index_new_note">
  <%= simple_form_for @note do |f| %>
    <td class="class_col"><%= f.date_field :date , label: false %><br><div class="notetitle"><%= f.input :title, placeholder: 'class', label: false %></div><div class="index-instructor"><%= f.input :instructor, placeholder: 'instructor', label: false %></td>
    <td id="index_tag_input"><%= f.input :tag_list, placeholder: '#tag', label: false %><%= f.input :tag_list, placeholder: '#tag', label: false %><%= f.input :tag_list, placeholder: '#tag', label: false %></td>
    <td><%= f.input :technique, as: :text, placeholder: 'technique' , label: false, :input_html => {:rows => 3} %></td>
    <td><%= f.input :sparring, as: :text, placeholder: 'sparring' , label: false, :input_html => {:rows => 3}%></td>
    <td><%= f.submit '+', class: 'index_create_note' %></td>
    <% end %>
  </tr>

    <% @notes.each do |note| %>
    <tr data-link="<%= edit_note_path(note)%>", class= "index-table-rows">
      <td><%= format_date(note) %><br><div class="notetitle"><%= format_title(note) %></div><div class="index-instructor"><%= note.instructor.downcase%></td>
      <td><% format_tags(note).each do |tag| %>
        <button class="tag-badge"><%= "##{tag}" %></button><br>
      <% end %></td>
      <td><%= truncate(note.technique, :length => 150, :separator => '') %></td>
      <td><%= truncate(note.sparring, :length => 150, :separator => '') %></td>
      <td></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @notes, :page_links => false %>

app/views/shared/_table_tag_cloud.html.erb
<div class="table_cloud">
  <div class="title_headers">
    <h1 id="dynamic-title"><%= table_header(request.path_info) %></h1>
    <h1 class="classnotestitle">ClassNotes</h1>
  </div>
<ul class="nav-top-links">
  <li class="nav-item">
    <%= link_to new_note_path, method: :get, class: "nav-link align-middle px-0" do %>
    <span class="ms-1  d-sm-inline">New Note</span>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to root_path, class: "nav-link align-middle px-0" do %>
    <span class="ms-1  d-sm-inline">All Notes</span>
    <% end %>
  </li>

</ul>
  <% @notes.tag_counts.order("tags.name").each do |tag| %>
  <%= link_to "##{tag.name.parameterize(separator: '_')}", tag_path(tag.name), class: "nav-tag" %>
  <% end %>
  <ul class="nav-bottom-links">
    <li class="nav-item">
      <%= link_to edit_user_registration_path, method: :get, class: "nav-link align-middle px-0" do %>
      <span class="ms-1  d-sm-inline">Profile</span>
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to destroy_user_session_path, method: :delete, class: "nav-link align-middle px-0" do %>
      <span class="ms-1  d-sm-inline">Sign Out</span>
      <% end %>
    </li>

  </ul>
</div>

app/views/shared/_tagcloud.html.erb
<div class="tag_section">
  <div class="collapse" id="tagCloudCollapse">
    <div class="card card-body" id="tagcloudBody">
      <% @notes.tag_counts.order("tags.name").each do |tag| %>
      <li class="tag-badge">
        <%= link_to "##{tag.name.parameterize(separator: '_')}", tag_path(tag.name), class: "tag-cloud-badge" %></li>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_topnav.html.erb
<div class="topnav">
    <button class="openbtn" onclick="openNav()">&#9776;</button>
    <h1 id="dynamic-title"><%= table_header(request.path_info) %><% if show_tag_toggle(request.path_info) %><a
        class="btn btn-primary" data-bs-toggle="collapse"
        href="#tagCloudCollapse" role="button" aria-expanded="false" aria-controls="tagCloudCollapse"
        id="tag_cloud_toggle">
        +
      </a><% end %></h1>
    <div id="emptydiv"></div>
    <h1 class="classnotestitle">ClassNotes</h1>
    <div class="title-replacement"></div>
  </div>

  